name: RayKits
main: ru.raytrace.Main
version: 1.0
author: Raytrace
commands:
  addkit:
    description: this command allows to add new kit to the store
    usage: /<command> kitName price
    permission: raykits.add
    permission-message: Error! Need raykits.add permission
  buykit:
    description: this command allows to buy kit from the store
    usage: /<command> kitName for buy or /<command> for show list
  delkit:
    description: this command allows to delete kit from the store
    usage: /<command> kitName
    permission: raykits.del
    permission-message: Error! Need raykits.del permission